"""initial system schema

Revision ID: 0001
Revises:
Create Date: 2026-06-18 04:46:35.785998
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "export_tokens",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("remote", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("token"),
    )
    with op.batch_alter_table("export_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_export_tokens_expires_at"), ["expires_at"], unique=False
        )

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_key"))

    op.drop_table("jobs")
    with op.batch_alter_table("export_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_export_tokens_expires_at"))

    op.drop_table("export_tokens")
    op.drop_table("config")
    # ### end Alembic commands ###
